### ISSUE TITLE
Deep Selectors

### ISSUE THREAD

**Issue by lizidev** [abishekatp/stylers#19]
I want a selector in scoped styles to be "deep", i.e. affecting child components.
like vue: https://vuejs.org/api/sfc-css-features.html#scoped-css

**Comment by abishekatp** [comment]
Thank you for opening an issue. I will try to add this feature before this week end.

**Comment by luoxiaozero** [comment]
Ok, looking forward to it

**Comment by abishekatp** [comment]
I have added the above implementation. but I want to make sure weather this approach will be feasible before merging this branch

**Comment by luoxiaozero** [comment]
![R4HQBXT} 2XMP3O~NE9FGLR](https://user-images.githubusercontent.com/48741584/228447335-a2de5c44-aef8-4e6b-8816-40418bfcead4.png)
When :deep is preceded by a child selector is error

**Comment by abishekatp** [comment]
Yeah I have also noticed that and puhing another implementation.

**Comment by luoxiaozero** [comment]
ok

**Comment by luoxiaozero** [comment]
No more questions

**Comment by abishekatp** [comment]
Yeah okay. I will merge and release it by end of today.
