### ISSUE TITLE
Does not work with SVG properties

### ISSUE THREAD

**Issue by svieujot** [abishekatp/stylers#37]
The properties in https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute need to be added to the file `stylers/src/style/css_style_declar.rs` in `ALL_PROPERTIES` to prevent errors with SVG properties.

**Comment by svieujot** [comment]
Also the SVG tags need to be added.

For example the following declaration makes the macro panic:
```
div polygon {
    fill: red;
}
```

**Comment by abishekatp** [comment]
Hi, @svieujot  Thank you reporting bug and fixing it. I will merge and release new version today for this.

**Comment by abishekatp** [comment]
> Also the SVG tags need to be added.
> 
> For example the following declaration makes the macro panic:
> 
> ```
> div polygon {
>     fill: red;
> }
> ```

is this problem still persists after the above fix?

**Comment by svieujot** [comment]
> > Also the SVG tags need to be added.
> > For example the following declaration makes the macro panic:
> > ```
> > div polygon {
> >     fill: red;
> > }
> > ```
> 
> is this problem still persists after the above fix?

No this is actually not a direct problem.

It is just that in most cases this rule needs to be written as `div :deep(polygon) {...`.
